### ISSUE TITLE
Mobx performance vs S.js

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/mobx-jsx#1]
Feel free to disregard this question but you may be one of the few people who can answer this.  Do you  know anything about the raw performance (ignoring React/dom rendering) of Mobx  vs S.js?  Even if it's just an intuition, anything you could offer would be helpful.   S.js comes across as substantially faster but perhaps that is not the case.

**Comment by ryansolid** [comment]
You are correct in that I've been able to do more apples to apples sort of comparison here by running both libraries (as well as Knockout) through essentially the same paces to see how they perform with the same underlying renderer. I generally use the JS Framework Benchmark, and a modified version of Jeremy Ashkenas Circles(300 and I measure run to run instead of just active code) test to get an idea of performance characteristics. The first covers all the typical single operation batch row reconciliation algorithms. And the second exercises how well the library handles constant partial updates (it animates a bunch of moving circles with setTimeout 0)

The tricky part is that I have no control. As in while I can compare against Vanilla JS in all the different benchmarks I've done the renderer is built around fine grained updates like those that S, MobX, and Knockout do so to what degree is substantial is a bit harder since the comparison is always against the best performing of the 3 which is S. I also didn't publish that or break that out from Solid (which is built on S.js) so I can see how the results are a bit more muddled on JS Frameworks Benchmark. A pure S implementation with my renderer is similar to Surplus, but a little bit faster for adding and removing many rows and a tiny bit lower on memory. Otherwise basically identical.

Rather than just point out how S is pretty much faster in every dimension, I want to give a bit insight why. From pure raw performance Knockout actually slots in between S and MobX in simple tests. Seems surprising but it's because MobX and Solid are both at a bit of a disadvantage compared to S and Knockout. Knockout is ancient by comparison and is a memory hog (which catches up with it in practice) but like S it's all about simple Signals. That memory shows up however when you need to free it on clear row benchmarks or when you are doing rapid updates like in the Circles test. 

My results for the circles test look something like (per loop):
Vanilla: 7ms
Surplus: 7.6ms
Solid: 7.65ms
Mobx-JSX: 7.75ms
Ko-JSX: 14.5ms
React: 26.5ms (this is a really bad test for VDom libraries)

Anyway why is MobX and Solid are generally at a disadvantage comes down they use heavier constructs as the defaults. A MobX observable and Solid State objects are nested proxies and the use of getter/setters has a real overhead. Boxed values would be a better comparison to S.js but I have to admit I've never done that as it isn't how you typically program with MobX. I've found that with inserting 10,000 rows a do nothing nested proxy on my computer has about 50ms overhead. That's not accounting for anything else that happens in those getter and setters.

Admittedly out of all the libraries I'm the least familiar with MobX. It's more of a demonstration of this approach over React's VDOM rather than a testament to the performance of MobX itself. I ended up not using their built in methods for reconciling arrays. I found their transformers to be slower than the method used in S-array (and Solid, ko-jsx, mobx-jsx). There is a lot more there in the API that I might not be leveraging to best effect.

So is S.js substantially faster than MobX? On a scale of Vanilla to React, no. If you tighten it up to Vanilla to Inferno, definitely.  S outperforms it pretty much across the board. However, MobX makes things a lot easier and has worked through a lot more problems at which the tradeoff of implementing those solutions yourself has a real cost. I started this area writing my own change detection library that also was slower than S and similar to MobX in performance, but just gave up at a certain point and decided S.js was likely to be better in performance than anything I'd do myself. So instead I focused on rendering techniques and Proxies to give MobX like capability with performance of S.js. As you can see Solid also outperforms MobX which while some of it is clever performance oriented use of Proxies mostly is a testament to underlying performance of S.js.

Outside of any raw performance numbers, the lower memory overhead of S.js is probably the ultimate winner here as it tends to scale better. I'm yet to benchmark my Solid State container for React which might be a more natural place to compare S to MobX where both are being restricted by React's VDOM. Although MobX getting away from React is really enough of a win. MobX with React will always be less performant than optimally written React code which is a shame since React is the much larger bottleneck.

**Comment by mrjjwright** [comment]
This is an unbelievably awesome answer and gigantically helpful, thank you so ever much.   This is just the kind of insight on which I can build my own.  🔥

**Comment by mrjjwright** [comment]
You inspired me to try something that I invited you to.  Feel free to ignore, but thought you might want to take a peek.  I am going to build a spreadsheet like editor on top of this but it uses a lot of lower level ideas you love from Mobx and S.js and that I am learning from you guys.   My email is mrjjwright@gmail.com or just leave an issue asking me to remove you.
