### ISSUE TITLE
'r' is not defined when building with Parcel.

### ISSUE THREAD

**Issue by NinZine** [ryansolid/mobx-jsx#2]
This is a great effort, loving it so far.

Building with Parcel and trying to run it I get.
`Uncaught ReferenceError: r is not defined`

As an ugly workaround I did like this:

`
import { r as a } from 'mobx-jsx';
const r = a;
`

And then it is defined in the scope. Any clues why `rollup` and `parcel` build output is different in this sense? Thanks.

**Comment by ryansolid** [comment]
Hmm.. this isn't the first time people have had similar issues. Admittedly I regularly use Rollup and Webpack and am yet to try Parcel.  Someone early on was having similar issue in webpack, but I never hit it in webpack. It has to be aggressive tree shaking that assumes that it is never used and removes it before the Babel/JSX compile step. I know similar libraries like Surplus/HyperApp have these sort of issues with Typescript but Parcel specifically I'm not sure unless it's build chain order.

I imagine most JSX libraries would have this issue as they compile down a similar way. I used r (for renderer instead of h for html) but it's same idea. Doing a Google search only netted me issues with Typescript compilation like [this one](https://github.com/parcel-bundler/parcel/issues/1487). I don't know Parcel well enough to know what other scenarios would let something like that occur.

**Comment by NinZine** [comment]
I think you are on to something. I checked the generated code for more clues.

```
},{"babel-plugin-jsx-dom-expressions":"node_modules/babel-plugin-jsx-dom-expressions/dist/createRuntime.js","mobx":"node_modules/mobx/lib/mobx.module.js"}],"src/main.jsx":[function(require,module,exports) {
"use strict";

var _mobx = require("mobx");

var _mobxJsx = require("mobx-jsx");

.....

var App = function App() {
  return function () {
    var _el$8 = _tmpl$4.content.firstChild.cloneNode(true),
        _el$9 = _el$8.firstChild,
        _el$10 = _el$9.nextSibling;

    r.insert(_el$10, Number());
    return _el$8;
  }();
};
```

There is no `r` in that calling scope, because the `require` is assigned to `_mobxJsx`.
The workaround adds this line:

```
var r = _mobxJsx.r;
```

I don't have enough knowledge about how this transpiling works to dig much deeper unfortunately.

**Comment by ryansolid** [comment]
Ok so the commonjs compiled version isn't handling the named exports. Is it your intention (or Parcel's) to for it to endup with commonjs require statements. I'm gathering this is because it's being transpiled to ES5. Like for instance when I use Babel with webpack I set preset env with modules false to keep them as ES modules since webpack knows how to read them.
```
presets: [['@babel/preset-env', {modules: false}]]
```
Even with require I would have expected it to assign the r var right after since the code is indicating that it wants that symbol. I suppose it could just mangle it throughout the rest of the file and still be consistent.

If atleast it is coming out at _mobxJsx.r. Your other option is to pass an optional argument to the babel-plugin-jsx-dom-expressions where you can can change what it uses for r. For example:

```
plugins: [['jsx-dom-expressions', {moduleName: '_mobxJsx.r']]
```

**Comment by NinZine** [comment]
I could not get option 1 working.
But passing in the optional argument worked.

```
plugins: [['jsx-dom-expressions', {moduleName: '_mobxJsx.r']]
```

Thanks!

**Comment by ryansolid** [comment]
Pursuing a similar issue in Solid https://github.com/ryansolid/solid/issues/20 I realized there was an issue in the babel plugin. This should be fixed now so you shouldn't have to do any of the special hacks. The default options should just work.
