### ISSUE TITLE
transform lit / h syntax babel plugin

### ISSUE THREAD

**Issue by jeremy-coleman** [ryansolid/mobx-jsx#5]
check out https://github.com/developit/htm/tree/master/packages/babel-plugin-htm

**Comment by ryansolid** [comment]
You could use that I suppose. I'm unclear what the suggestion is.

I will say this much in terms of a library like this transforming from tagged Template Literals to HyperScript is a deoptimization. Doing this would actually slow thing down.

This library already ships with HyperScript and Tagged Template literal versions that can be run without precompilation. However, using the JSX Babel transformation is the most performant, but Tagged Template Literals is close behind even though it's 100% runtime. HyperScript is a good chunk slower. Unlike the Virtual DOM that essentially turns JSX, Tagged Template Literals, you name it down to HyperScript the output that JSX and Tagged Template can create from analyzing the HTML structure is more performant for this sort of library.

It would be possible to compile the Tagged Template Literals to same output as the JSX but at that point I'd argue you should use the JSX.

For more info read my latest article on Medium(don't worry it's a non-paywall link) where I cover this in detail:
https://medium.com/@ryansolid/the-fastest-way-to-render-the-dom-e3b226b15ca3?source=friends_link&sk=5ae1688dde789e46cecf5c976e708da5

I am using Solid my own change library but all the above applies to MobX which is realistically is only a few points slower.

**Comment by jeremy-coleman** [comment]
I was just suggesting it as an option to optimize tagged template literals while still keeping 0 build requirements, for all of your tagged template libs

**Comment by ryansolid** [comment]
Of course, thank you for the suggestion. I sometimes forget how close I am to all this.

Basically I added HyperScript support for these sort of reasons to be compatible with existing tooling. However, from a performance standpoint I haven't been able to leverage them (otherwise I wouldn't have had to roll my own). This comes down to fact that these Fine Grained Reactive graphs working on Real DOM nodes aren't subject to the 2 pass (construct, then diff/patch) of Virtual DOM libraries. The advantage is they can update with 0 passes, but it involves more work in initial setup. To offset that we get the biggest benefit from analysing ahead to determine what the optimal DOM operations are. As you can imagine HyperScript per element instructions, the dozen of "h" calls obscures this and is much easier for constructing nodes on the fly. In so unlike in a Virtual DOM library where all the DSL wrappers over HyperScript are just an extra runtime cost you'd want to compile away, in these libraries it is actually  HyperScript which circumvents the biggest advantage available to us.

This is why I linked the article. Believe it or not the Tagged Template Literals version(the way I'm using it for code generation) is faster at runtime than pretty much every Virtual DOM library. At first I was not expecting those sort of results but the truth is the slowdown that comes from one time at runtime code generation, for a library like this is significantly less than the overhead of unoptimal HyperScript execution.

I do see one big use for this though. IE11 compatibility for a runtime solution. That way we theoretically could use this with MobX 4 and IE11 and still use Tagged Template Literals and then produce a legacy compatible version. I will update the docs.
