### ISSUE TITLE
Conditional rendering

### ISSUE THREAD

**Issue by sdcdsvsdv423** [ryansolid/mobx-jsx#9]
Hello,
how to implement conditional rendering?

I am trying to do something like that, but id does not work. I expect that `AuthForm` will be replaced by `HomePage` component, but nothing happens. ([codesandbox](https://codesandbox.io/s/mobx-counterfunctions-vrfxx?fontsize=14))

```ts
import { observable } from "mobx";
import { render } from "mobx-jsx";


function AuthForm() {
  return <div>Authorization form</div>;
}

function HomePage() {
  return <div>Home page</div>;
}

const appState = observable({
  authorized: false
})

setTimeout(() => {
  appState.authorized = true
}, 1000)

function App() {
  const Component = appState.authorized ? HomePage : AuthForm;

  return <div><Component/></div>
}

render(App, document.getElementById("app"));
```

**Comment by ryansolid** [comment]
Unlike a library like React, the render function/Component doesn't rerun. It only runs once. It's the bindings that do. So in MobX terms, instead of picturing the whole Component wrapped in an `autorun` each expression is. Basically it's the exact opposite of React hooks. It's the Hooks that run multiple times not the Component.

In your case, putting the logic in the view might be what you are after.

```jsx
return <div>{appState.authorized ? <HomePage/> : <AuthForm/>}</div>
```
You can also extract this out into a function if you don't want to stick it all in the JSX. But the mentality here is if it isnt in a reaction(autorun/computed) or in a binding it isnt updating.

**Comment by sdcdsvsdv423** [comment]
I've updated your example and now both of the components are displaying.
<img width="644" alt="Снимок экрана 2019-11-07 в 18 32 03" src="https://user-images.githubusercontent.com/5320711/68381612-10143e00-018d-11ea-91d7-d973110497e7.png">

**Comment by sdcdsvsdv423** [comment]
Thank you for the explanation. If there are more than 2 components, it's not possible to switch them dynamically, does it?

**Comment by ryansolid** [comment]
While I'm not exactly sure why it's doing that (something for me to look into), there is a bug in the code that if you fix resolves your issue. Make sure the ternary is returning Components like:
```jsx
return <div>{appState.authorized ? <HomePage/> : <AuthForm/>}</div>
```

As for more than 2. There are a few options. Simplest might be just wrapping the conditions in function.

```jsx
function chooseComponent() {
  // do as many ifs or conditions as you want just return a Component instance.. ie. < />
}
return <div>{chooseComponent()}</div>
```
You could also inline it and execute or any trick people do with React in the JSX to drop block statements into JSX expressions but I think function is cleaner.

Remember since Components execute once it is fine to define functions in Component scope without worrying about performance overhead.

This paradigm might take a little to get used to if you haven't seen it before. But if you think about it, it is basically the same rules as MobX. If React wasn't doing the updates and you were doing DOM updates by just using `autorun` it would be like this. The render system is a bit more sophisticated than that but maybe that helps to visualize.

**Comment by sdcdsvsdv423** [comment]
Thank you!
